### ISSUE TITLE
PtrWeakKeyHashMap::entry sometimes incorrectly returns Vacant

### ISSUE THREAD

**Issue by Rua** [tov/weak-table-rs#1]
I have a `Vec` of `Rc`, and I store every one of the `Rc`s in a `PtrWeakKeyHashMap`. Then when I iterate through the vector and check if each one is present in the hashmap with `contains_key`, I correctly get `true` for each one. But if I also call `entry` in the same iteration, it sometimes returns `Vacant` right after `contains_key` returned `true`! The items in the vector which are incorrectly reported as vacant in the hashmap change each time the program is run, so it's hard to reproduce, but it's happening at least a few times out of 100 or so items.

**Comment by tov** [comment]
Wow, that's not good at all. Thanks for your report! Do you have any example code you can share?

Also, may I ask what you're using this for? You should know that this crate pretty, well, you could say experimental, as I don't fully know what I'm doing and haven't actually used it for anything.

**Comment by Rua** [comment]
Here is a simple example program that shows it for me. It mostly prints "all fine" but interspersed with the occasional "shouldn't happen".
```rust
use std::rc::{Rc, Weak};
use weak_table::PtrWeakKeyHashMap;
use weak_table::weak_key_hash_map::Entry;

fn main() {
	let mut rcs: Vec<Rc<u32>> = Vec::new();
	
	for i in 0..200 {
		rcs.push(Rc::new(i));
	}
	
	let mut weakmap: PtrWeakKeyHashMap<Weak<u32>, f32> = PtrWeakKeyHashMap::new();
	
	for item in rcs.iter().cloned() {
		let f = *item as f32 + 0.1;
		weakmap.insert(item, f);
	}
	
	for item in rcs.iter().cloned() {
		assert!(weakmap.contains_key(&item));
		
		match weakmap.entry(item) {
			Entry::Occupied(_) => println!("all fine"),
			Entry::Vacant(_) => println!("shouldn't happen!"),
		}
	}
}
```

**Comment by Czocher** [comment]
Tested it and reproduced the same problem both on debug and release. Rust version `rustc 1.33.0-nightly (b43986184 2019-01-11)`, `weak-table` version `0.2.3`.

**Comment by wdanilo** [comment]
@tov if this crate is experimental and not ready to be used, could you please write about it explicitly on the main GitHub page of this crate? I was looking for weak set and I almost used it until Ive read this topic.

**Comment by tov** [comment]
@wdanilo That’s a good point, thanks. I believe every crate with a sub-1.0 version number is experimental, though if this one has a bug that I haven’t fixed after this many months then it’s more experimental than many. As a first step I’m going to add the above to the tests so that it shows that CI is failing, and then if I still can’t fix it soon I’ll add a note. Thanks.

**Comment by DerSaidin** [comment]
For my own curiosity: [search for GitHub repos which use this crate](https://github.com/search?l=TOML&q=weak-table&type=Code)
