### ISSUE TITLE
Support for tokio::broadcast::Sender.

### ISSUE THREAD

**Issue by cheako** [tov/weak-table-rs#5]
This may seem out of scope, as this type isn't a weak reference.  However I feel it's an important target for pub_sub implementations.

I wrote my own implementation:
https://gitlab.com/cheako/websuite-rs/-/blob/2204ec54f60f45789925d0b5839bf2a18d6a5b40/naomi/src/lib.rs

The limiting factor is that `tokio::broadcast::Sender` can produce `tokio::broadcast::Receiver`(s), the reverse is not true and I feel that this is a requirement for weak-table?

**Comment by tov** [comment]
Hey @cheako, are you still interested in this? Sorry for being so slow. I have time to look into it now if you think it still makes sense. Also, I don’t quite understand your example yet. Is there a sense in which the sender is weak and the receiver strong, or vice versa?

**Comment by cheako** [comment]
I think what happened with this project is encryption, even if done in wasm, in the browser is slow.  I tried to use indexeddb to cache results, but didn't understand what I was doing.

As for this feature, I've my own thing and AFAIK it works well enough where I don't think I'd switch to using weak-table.  I don't remember the problem I was trying to solve, sorry.  From the description here, I think the task was to lookup a `Sender` from a `Receiver`...  So a broadcast could be done by any listener, not sure if that level of detail matters for a container type.

**Comment by tov** [comment]
Okay, I looked into it more, and I think that without being able to turn a `Receiver` back into a `Sender`, this API doesn’t make sense. I’m glad your own thing is working well enough :)
